
syn keyword cType B H W UB UH UW UD F D ER
syn keyword cType REG_S8BIT REG_U8BIT REG_S16BIT REG_U16BIT REG_S32BIT REG_U32BIT
syn keyword cType PORT FLAG_REG

syn keyword cStorageClass REGISTER PUBLIC PRIVATE LOCAL EXTERN CONST INLINE ROM_CONST FAR

syn keyword cConstant TRUE FALSE SET CLEAR HI LO HIGH LOW ON OFF OK NG
syn keyword cConstant E_OK E_PAR E_QOVR E_TMOUT E_ERR E_BUSY E_FMTERR E_RETRYERR
syn keyword cConstant E_ABORT E_CANCEL E_NACK E_ARBT E_BERR
